"""The device-environment operations a step may trigger, injected by the runner."""

from __future__ import annotations

from typing import Protocol


class DeviceControl(Protocol):
    """Device-environment operations a step may trigger (simctl on iOS, adb on Android). Injected by
    the runner so the orchestrator stays backend-agnostic; None means unavailable (the fake driver,
    or parallel runs which don't pin a single device). A backend that backs only part of the family
    (the Android emulator) raises UnsupportedAction for the rest, guarded up front by preflight."""

    def set_location(self, lat: float, lon: float) -> None: ...
    def push(self, payload: dict[str, object]) -> None: ...
    def clear_keychain(self) -> None: ...
    def clear_clipboard(self) -> None: ...
    def set_clipboard(self, text: str) -> None: ...
    def get_clipboard(self) -> str: ...
    def home(self) -> None: ...
    def foreground(self) -> None: ...
    def override_status_bar(self, **kwargs: str | int) -> None: ...
    def clear_status_bar(self) -> None: ...
